const SET_FORMDATA = 'SET_FORMDATA';
const CLEAR_FORMDATA = 'CLEAR_FORMDATA';
const SET_LOADING = 'SET_LOADING';
const SET_DATA = 'SET_DATA';
const SET_CACHESTATE = 'SET_CACHESTATE';
const FILTER_DATA = 'FILTER_DATA';
const SET_SEARCHKEY = 'SET_SEARCHKEY';
const SET_FILTERED_DATA_BY_KEY_WORD = 'SET_FILTERED_DATA_BY_KEY_WORD';
const SIGN_UP = 'SIGN_UP';
const LOG_IN = 'LOG_IN';
const LOG_OUT = 'LOG_OUT';

module.exports = {
	SET_FORMDATA,
	CLEAR_FORMDATA,
	SET_LOADING,
	SET_DATA,
	SET_CACHESTATE,
	FILTER_DATA,
	SET_SEARCHKEY,
	SET_FILTERED_DATA_BY_KEY_WORD,
	SIGN_UP,
	LOG_IN,
	LOG_OUT,
};
