steps:
    # Install dependencies
    - name: 'gcr.io/cloud-builders/npm'
      entrypoint: 'npm'
      args: ['install']
      dir: 'frontend/rasjobs'

    # Build the application
    - name: 'gcr.io/cloud-builders/npm'
      entrypoint: 'npm'
      args: ['run', 'build']
      dir: 'frontend/rasjobs'

    # Deploy to target environment
    - name: 'gcr.io/cloud-builders/gcloud'
      entrypoint: 'gcloud'
      args:
          - 'gcloud storage rsync'
          - '-r'
          - 'frontend/rasjobs/build/'
          - 'user@example.com:/path/to/deploy'
